minimum_position: [-450,300.0]
maximum_position: [50.0,600.0]
minimum_velocity: [0,-20.0]
maximum_velocity: [10.0,20.0]
input_boid_count: 50
input_move_to_middle_strength: 0.01
input_alert_distance: 100
input_formation_flying_distance: 10000
input_formation_flying_strength: 0.125

